# Generated by Codex on 2026-06-20

import django.db.models.deletion
from django.db import migrations, models


def ensure_employee_roster_records(apps, schema_editor):
    User = apps.get_model("users", "User")
    Employee = apps.get_model("employees", "Employee")
    EmployeeSalary = apps.get_model("payments", "EmployeeSalary")
    EmployeeOvertime = apps.get_model("payments", "EmployeeOvertime")
    Payslip = apps.get_model("payments", "Payslip")
    EmployeeLeave = apps.get_model("leave", "EmployeeLeave")
    EquipmentIssue = apps.get_model("equipments", "EquipmentIssue")

    referenced_user_ids = set()
    for model in (EmployeeSalary, EmployeeOvertime, Payslip, EmployeeLeave, EquipmentIssue):
        referenced_user_ids.update(
            model.objects.exclude(employee_id__isnull=True).values_list("employee_id", flat=True)
        )

    for user in User.objects.filter(id__in=referenced_user_ids):
        if Employee.objects.filter(id=user.id).exists():
            continue

        Employee.objects.create(
            id=user.id,
            first_name=user.first_name or user.username or "Employee",
            last_name=user.last_name or "Record",
            gender=user.gender or "Male",
            phone_number=user.phone_number or "",
            id_number=user.id_number,
            nhif_number=user.nhif_number,
            nssf_number=user.nssf_number,
            kra_pin=user.kra_pin,
            position_id=user.position_id,
            postal_address=user.postal_address,
            physical_address=user.physical_address,
            town=user.town,
            county=user.county,
            country=user.country,
            basic_salary=user.basic_salary,
            status="Available",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0032_employee_workshift"),
        ("equipments", "0013_alter_vehicle_vehicle_type"),
        ("leave", "0002_alter_employeeleave_status"),
        ("payments", "0009_bankinformation"),
    ]

    operations = [
        migrations.RunPython(ensure_employee_roster_records, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employeesalary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeeovertime",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.employee",
            ),
        ),
    ]