# Generated by Django 6.0.3 on 2026-06-20 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_deploymentassignment'),
        ('payments', '0010_use_employee_roster_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Fixed amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PAYEBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('relief_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['lower_limit'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Employment Contract', max_length=255)),
                ('pay_basis', models.CharField(choices=[('Daily', 'Daily work'), ('Monthly', 'Monthly salary')], max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
            options={
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pay_basis', models.CharField(choices=[('Daily', 'Daily work'), ('Monthly', 'Monthly salary')], max_length=20)),
                ('days_worked', models.PositiveIntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('common_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('personal_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.employeecontract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction'), ('Tax', 'Tax')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payroll_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.payrollline')),
            ],
            options={
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processed', 'Processed')], default='Draft', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-created'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='payrollline',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.payrollrun'),
        ),
        migrations.CreateModel(
            name='PersonalDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Fixed amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_deductions', to='employees.employee')),
            ],
            options={
                'ordering': ['employee', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='payrollline',
            unique_together={('payroll_run', 'employee')},
        ),
    ]
