# Generated by Django 6.0.3 on 2026-06-20 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_commondeduction_payeband_employeecontract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Fixed amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payments.employeecontract')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
