# Generated by Codex on 2026-06-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_use_employee_roster_records"),
        ("equipments", "0013_alter_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentissue",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.employee",
            ),
        ),
    ]