# Generated by Codex on 2026-06-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_use_employee_roster_records"),
        ("leave", "0002_alter_employeeleave_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeleave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employees.employee",
            ),
        ),
    ]