from django.urls import path
from apps.payments.views import (
    create_common_deduction,
    create_contract,
    create_contract_allowance,
    create_paye_band,
    create_personal_deduction,
    edit_common_deduction,
    edit_contract,
    edit_contract_allowance,
    edit_paye_band,
    edit_personal_deduction,
    employee_salaries,
    generate_payroll,
    payslip_receipt,
    payroll_configurations,
    payroll_contract_detail,
    payroll_contracts,
    payroll_dashboard,
    payroll_deductions,
    payroll_payslip,
    payroll_paye,
    payroll_personal_deductions,
    payroll_run_detail,
    payroll_runs,
    overtimes,
    record_overtime,
    payslips,
    generate_payslips,
    delete_payslip,
    new_bank_details,
    edit_bank_details,
)

urlpatterns = [
    path("payroll/", payroll_dashboard, name="payroll-dashboard"),
    path("payroll/contracts/", payroll_contracts, name="payroll-contracts"),
    path(
        "payroll/contracts/<int:contract_id>/",
        payroll_contract_detail,
        name="payroll-contract-detail",
    ),
    path("payroll/paye/", payroll_paye, name="payroll-paye"),
    path("payroll/deductions/", payroll_deductions, name="payroll-deductions"),
    path(
        "payroll/configurations/",
        payroll_configurations,
        name="payroll-configurations",
    ),
    path(
        "payroll/personal-deductions/",
        payroll_personal_deductions,
        name="payroll-personal-deductions",
    ),
    path("payroll/runs/", payroll_runs, name="payroll-runs"),
    path("payroll/contracts/new/", create_contract, name="create-contract"),
    path("payroll/contracts/edit/", edit_contract, name="edit-contract"),
    path(
        "payroll/contract-allowances/new/",
        create_contract_allowance,
        name="create-contract-allowance",
    ),
    path(
        "payroll/contract-allowances/edit/",
        edit_contract_allowance,
        name="edit-contract-allowance",
    ),
    path(
        "payroll/common-deductions/new/",
        create_common_deduction,
        name="create-common-deduction",
    ),
    path(
        "payroll/common-deductions/edit/",
        edit_common_deduction,
        name="edit-common-deduction",
    ),
    path("payroll/paye-bands/new/", create_paye_band, name="create-paye-band"),
    path("payroll/paye-bands/edit/", edit_paye_band, name="edit-paye-band"),
    path(
        "payroll/personal-deductions/new/",
        create_personal_deduction,
        name="create-personal-deduction",
    ),
    path(
        "payroll/personal-deductions/edit/",
        edit_personal_deduction,
        name="edit-personal-deduction",
    ),
    path("payroll/generate/", generate_payroll, name="generate-payroll"),
    path("payroll/runs/<int:run_id>/", payroll_run_detail, name="payroll-run-detail"),
    path("payroll/payslips/<int:line_id>/", payroll_payslip, name="payroll-payslip"),
    path("salaries/", employee_salaries, name="salaries"),
    path("overtimes/", overtimes, name="overtimes"),
    path("record-overtime/", record_overtime, name="record-overtime"),
    path("payslips/", payslips, name="payslips"),
    path("generate-payslips/", generate_payslips, name="generate-payslips"),
    path("delete-payslip/", delete_payslip, name="delete-payslip"),
    path("payslip-receipt/<int:id>/", payslip_receipt, name="payslip-receipt"),
    path("new-bank-details/", new_bank_details, name="new-bank-details"),
    path("edit-bank-details/", edit_bank_details, name="edit-bank-details"),
]
