# Generated by Codex on 2026-06-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def seed_current_deployments(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    DeploymentAssignment = apps.get_model("employees", "DeploymentAssignment")

    for employee in Employee.objects.exclude(workstation_id__isnull=True):
        if DeploymentAssignment.objects.filter(employee_id=employee.id, status="Active").exists():
            continue

        DeploymentAssignment.objects.create(
            employee_id=employee.id,
            client_id=employee.client_id,
            workstation_id=employee.workstation_id,
            work_shift=employee.workshift,
            status="Active",
            assigned_at=employee.modified or employee.created or timezone.now(),
            notes="Seeded from current employee assignment.",
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_alter_jobrole_category_alter_jobrole_group"),
        ("employees", "0032_employee_workshift"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("work_shift", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Reassigned", "Reassigned"),
                            ("Ended", "Ended"),
                        ],
                        default="Active",
                        max_length=255,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployments",
                        to="core.client",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_history",
                        to="employees.employee",
                    ),
                ),
                (
                    "workstation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployments",
                        to="core.workstation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(seed_current_deployments, migrations.RunPython.noop),
    ]